language: node_js
node_js:
- '8'
services:
- docker
install:
- npm i
- npm run lint
- npm run docker
deploy:
  - provider: cloudfoundry
    api: https://api.run.pivotal.io
    username: david.ahern26@gmail.com
    password:
      secure: ce1MwlT1wbb80F+m2sxb2vIB4CcunsI9SEPyjWcXAifAvkEEm0LyyW63bzsyJ3QpujsfyQWIL7dtbLjw1RHQ1UQlI/We5tFvIWCyOr/FW5D5INNGTEXQSS9k+kWCAxkHgwsqC3UXhn0Lf8XMbq7n8ii9E+SSEnS52H81+vbSunOB9em7DLmb26WPcEfA3KVpCxeu+6gBG4MQfUe4/qoGfNKsWS2+awdCgomCW/NeLbx12JYOhmNO8XgBPNlVbhQb8t3fxqoOiJm3HDRm9teZRh0jbRbDhlOufOCdSci0W3DN40vB781LoHr05nSRuqONEvp5wZQZrtvRl6wKyCay3PiNsWnlAttvm4oSVz8OOef44SA8e37oV6ISPH0+E72GhGgKx0sP+U02ILl35sdnEQZIeEfkD2ADiwkFC/8PXxabxfnI33UdrU8ZxzxazyXa8ba3jIZ9OqOihow1YJB249abdJMcnhIkBx+SRc8xCl6651mQfbFUmeBVzzjGWxc66BxalXOYgrQfX2eWH7pT5mfvmqnh47xiyc/QKhif5nOsV87CXDw+2RH8affqWhap2UmVoJmV5gbPcOn4PG0euC1xjliShJEF7Wjl3kXNyWai7XMkEkurOWwexVCYD6cIrM9EoDtpnxeR7f8McaGjn9qysPUs6SvkKEABOohvo6U=
    organization: thor
    space: dev
    on:
      repo: msc-blog-assignment/msc-blog-avatar-api
      branch: master
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && yarn docker:tag && yarn docker:push
    on:
      branch: master
